apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
commonLabels:
  env: dev
replicas:
- count: 0
  name: adservice
- count: 0
  name: cartservice
- count: 0
  name: checkoutservice
- count: 0
  name: currencyservice
- count: 0
  name: emailservice
- count: 0
  name: frontend
- count: 0
  name: loadgenerator
- count: 0
  name: paymentservice
- count: 0
  name: productcatalogservice
- count: 0
  name: recommendationservice
- count: 0
  name: redis-cart
- count: 0
  name: shippingservice
images:
- name: gcr.io/google-samples/microservices-demo/frontend
  newName: ghcr.io/amargmail/boutique-frontend
  newTag: sha-b3e33ef
