grafana:
  adminPassword: "admin"
  defaultDashboardsTimezone: browser

# FIX FOR KIND CLUSTERS: Disable control plane scraping
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false # <--- Added this to fix the connection refused error

prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    retention: 2d
