# 1. Configure Grafana
grafana:
  adminPassword: "admin" # Simple password for local portfolio
  defaultDashboardsTimezone: browser
# 2. Tune Prometheus to use less RAM (Staff Level FinOps/Resource Management)
prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    retention: 2d # Only keep 2 days of data instead of 15
    resources:
      requests:
        memory: 400Mi # Cap memory usage
# 3. Disable heavy components we don't need for this demo
alertmanager:
  enabled: false
prometheusOperator:
  admissionWebhooks:
    enabled: false
