apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-perf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AmarGmail/sre-portfolio-boutique.git'
    targetRevision: HEAD
    path: apps/boutique/overlays/perf
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: perf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
